name: DockerHub
on:
  workflow_dispatch:
  push:
    branches: 
      - v3
  schedule:
    - cron: '0 21 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.MY_ID }}
          password: ${{ secrets.MY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: thisispatrick/jd-base:v3
